### ISSUE TITLE
crash: thread 'main' panicked at 'Failed to setup up sled store for Matrix SDK: ...'

### ISSUE THREAD

**Issue by pcarrin2** [ulyssa/iamb#143]
Sometimes when starting iamb, I get the following error (here it is with backtrace env var set):
```
thread 'main' panicked at 'Failed to setup up sled store for Matrix SDK: State(Backend(StoreError(Backend(Io(Custom { kind: Other, error: "could not acquire lock on \"/home/(my username)/.config/iamb/profiles/(profile name)/matrix/matrix-sdk-state/db\": Os { code: 11, kind: WouldBlock, message: \"Resource temporarily unavailable\" }" })))))', /home/(my username)/.cargo/registry/src/github.com-1ecc6299db9ec823/iamb-0.0.7/src/worker.rs:562:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
   2: core::result::unwrap_failed
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1791:5
   3: iamb::run::{{closure}}
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: iamb::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

iamb will keep crashing with this error for a while, then suddenly it will open properly.

Often iamb will freeze during use, and when I close/reopen my terminal and try to start it again, this problem will happen.

**Comment by pcarrin2** [comment]
Oh, I'm pretty sure this is due to a crashed iamb process not fully exiting/releasing a lock before I try to start a new one. The underlying problem is whatever causes iamb to freeze/crash; this is collateral that I can fix with a quick `killall iamb`.
