### ISSUE TITLE
'Session wasn't created nor shared"

### ISSUE THREAD

**Issue by nightshade427** [ulyssa/iamb#161]
I can login and decrypt my messages but when I try and send a message I get this error.

'Session wasn't created nor shared'

**Comment by ddanielgal** [comment]
I get the same error. I have a trace:
```
RUST_BACKTRACE=1 iamb                                                    
Logging in for @ddanielgal:beeper.com...
thread 'main' panicked at /home/den/.cargo/registry/src/index.crates.io-6f17d22bba15001f/matrix-sdk-crypto-0.6.0/src/session_manager/group_sessions.rs:162:50:
Session wasn't created nor shared
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_display
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:196:5
   3: core::panicking::panic_str
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:171:5
   4: core::option::expect_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/option.rs:1980:5
   5: matrix_sdk::room::joined::Joined::send_raw::{{closure}}.9603
   6: matrix_sdk::room::joined::Joined::send::{{closure}}.9582
   7: iamb::Application::iamb_run::{{closure}}.9563
   8: iamb::run::{{closure}}.8967
   9: tokio::runtime::runtime::Runtime::block_on
  10: iamb::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
<details>
<summary>Verbose trace here</summary>

```
RUST_BACKTRACE=full iamb                                                   
Logging in for @ddanielgal:beeper.com...
thread 'main' panicked at /home/den/.cargo/registry/src/index.crates.io-6f17d22bba15001f/matrix-sdk-crypto-0.6.0/src/session_manager/group_sessions.rs:162:50:
Session wasn't created nor shared
stack backtrace:
   0:     0x564097b11869 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x564097b11869 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x564097b11869 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x564097b11869 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5640968f5d60 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x5640968f5d60 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x564097adb1a2 - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x564097b13d3e - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x564097b13d3e - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x564097b134e0 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:272:22
  10:     0x564097b13052 - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x564096a74d4c - iamb::run::{{closure}}::{{closure}}::h6513e21aa591c019
  12:     0x564097b14377 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hbc5ccf4eb663e1e5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2029:9
  13:     0x564097b14377 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:783:13
  14:     0x564097b14090 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
  15:     0x564097b13fe6 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x564097b13fdf - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  17:     0x5640965fcd94 - core::panicking::panic_fmt::h784f20a50eaab275
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  18:     0x5640965fd372 - core::panicking::panic_display::h251010ce5e0560d5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:196:5
  19:     0x5640965fd372 - core::panicking::panic_str::h6f89534c81f0edc4
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:171:5
  20:     0x5640965fd372 - core::option::expect_failed::hc85eb6037a3050f7
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/option.rs:1980:5
  21:     0x564096c2c088 - matrix_sdk::room::joined::Joined::send_raw::{{closure}}::hcea79f39493e3818.9603
  22:     0x564096c1d5b0 - matrix_sdk::room::joined::Joined::send::{{closure}}::h0958604a34001bb8.9582
  23:     0x564096c01167 - iamb::Application::iamb_run::{{closure}}::h6bc5e9050e634dda.9563
  24:     0x564096bf0862 - iamb::run::{{closure}}::hb18c089899632df0.8967
  25:     0x564096f63776 - tokio::runtime::runtime::Runtime::block_on::hc419eb0326b24c22
  26:     0x5640974415b1 - iamb::main::h6617250a6f358415
  27:     0x564096750113 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb884eca64468b97d
  28:     0x564097436904 - main
  29:     0x7f8a23fbd14a - __libc_start_call_main
  30:     0x7f8a23fbd20b - __libc_start_main_impl
  31:     0x564096664cc5 - _start
  32:                0x0 - <unknown>
  ```

</details>

I am using a [Beeper](https://www.beeper.com/) account. The room in question is a bridged Facebook Messenger group chat. Beeper is using the https://github.com/mautrix/facebook bridge.
