### ISSUE TITLE
Tab completion panics for unrecognized commands

### ISSUE THREAD

**Issue by aw-bib** [ulyssa/iamb#81]
It seems that if I use `:vertical ro` and try to expand `rooms` via the tab-key `iamb` crashes

```
thread 'main' panicked at 'unknown command vertical', /home/arwagner/.cargo/registry/src/github.com-1ecc6299db9ec823/iamb-0.0.7/src/base.rs:868:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
   2: <modalkit::editing::buffer::EditBuffer<I> as modalkit::editing::action::Editable<(modalkit::editing::buffer::CursorGroupId,&modalkit::editing::base::ViewportContext<modalkit::editing::cursor::Cursor>,&C),modalkit::editing::store::Store<I>,I>>::editor_command
   3: <modalkit::widgets::textbox::TextBoxState<I> as modalkit::editing::action::Editable<C,modalkit::editing::store::Store<I>,I>>::editor_command
   4: iamb::run::{{closure}}.16163
   5: tokio::runtime::runtime::Runtime::block_on
   6: iamb::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

(same for `:horizontal ro<tab>`). 

- `iamb 0.0.7`
- Ubuntu 20.04.6 LTS (Focal Fossa)
- `rustc 1.68.0 (2c8cc3432 2023-03-06)`

via `cargo install --locked iamb`

**Comment by ulyssa** [comment]
Thank you for catching and reporting this! It looks like I made the default case for commands to panic when I added this in #44 , but then forgot to change it.
